package UAS;

import static UAS.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Made Artha
 * TGL 24 Mei 2025
 */
public class Sehat extends javax.swing.JFrame {
      DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form formBuku
     * @throws java.sql.SQLException
     */
    public Sehat() throws SQLException {
        initComponents();
        tabelData.setModel(dtm);
        dtm.addColumn("username");
        dtm.addColumn("password");
        dtm.addColumn("notelepon");
        dtm.addColumn("email");
         
       
        
        lsDtbuku();
        fieldEnabled(false);
        tombol(false);
        cBARU.setEnabled(true);
        cTUTUP.setEnabled(true);
        
        
    }
    private void fieldEnabled(boolean opsi){
    txusername.setEditable(opsi);
    txpassword.setEditable(opsi);
    txnotelepon.setEditable(opsi);
    txemail.setEditable(opsi);}
    
    private void tombol(boolean opsi){
    cBARU.setEnabled(opsi);
    cUBAH.setEnabled(opsi);
    cHAPUS.setEnabled(opsi);
    cTUTUP.setEnabled(opsi);
    }
     private void clearForm(){
         txusername.setText("");
         txpassword.setText("");
         txemail.setText("");
         txnotelepon.setText("");
     }
    private void lsDtbuku() throws SQLException{
      Connection cnn = koneksi();
      dtm.getDataVector().removeAllElements();
      dtm.fireTableDataChanged();
      if( !cnn.isClosed() ){
          PreparedStatement ps = cnn.prepareStatement("SELECT * FROM sehat;");
          ResultSet rs = ps.executeQuery();
          while( rs.next() ){
              Object[] dta = new Object[4];
              dta[0] = rs.getString("username");
              dta[1] = rs.getString("password");
               dta[2] = rs.getString("notelepon");
              dta[3] = rs.getString("email");
             
              
            dtm.addRow(dta);
          
          }
          cnn.close();
    }
    }
    private void storeData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("INSERT INTO sehat(username, password, notelepon, email) VALUES(?,?,?,?);");
        ps.setString(1, txusername.getText());
        ps.setString(2, txpassword.getText());
        ps.setString(3, txnotelepon.getText());
        ps.setString(4, txemail.getText());
        ps.executeUpdate();
        cnn.close();
    }
}

   private void updateData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement(
            "UPDATE sehat SET username=?, password=?, notelepon=? WHERE email=?;"
        );
        ps.setString(1, txusername.getText());
        ps.setString(2, txpassword.getText());
        ps.setString(3, txnotelepon.getText());
        ps.setString(4, txemail.getText()); // gunakan email sebagai kunci unik
        ps.executeUpdate();
        cnn.close();
    }
}

   private void destroyData() throws SQLException {
    Connection cnn = koneksi();
    if (!cnn.isClosed()) {
        String sql = "DELETE FROM sehat WHERE email = ?";
        PreparedStatement ps = cnn.prepareStatement(sql);
        ps.setString(1, txemail.getText()); // hapus berdasarkan email
        ps.executeUpdate();
        cnn.close();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txpassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txnotelepon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        cBARU = new javax.swing.JButton();
        cUBAH = new javax.swing.JButton();
        cHAPUS = new javax.swing.JButton();
        cTUTUP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HEALTHY MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("username");

        txusername.setBackground(new java.awt.Color(204, 255, 255));
        txusername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txusername.setForeground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("password");

        txpassword.setBackground(new java.awt.Color(204, 255, 255));
        txpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txpassword.setForeground(new java.awt.Color(153, 255, 255));
        txpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("notelepon");

        txnotelepon.setBackground(new java.awt.Color(204, 255, 255));
        txnotelepon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("email");

        txemail.setBackground(new java.awt.Color(204, 255, 255));
        txemail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        cBARU.setBackground(new java.awt.Color(0, 153, 204));
        cBARU.setText("Baru");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cUBAH.setBackground(new java.awt.Color(0, 153, 204));
        cUBAH.setText("Ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        cHAPUS.setBackground(new java.awt.Color(0, 153, 204));
        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        cTUTUP.setBackground(new java.awt.Color(0, 153, 204));
        cTUTUP.setText("Tutup");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("regist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txusername, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(cBARU)
                        .addGap(18, 18, 18)
                        .addComponent(cUBAH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cTUTUP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel6)))
                .addContainerGap(520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txnotelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBARU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cUBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
                                             
    if (!txusername.getText().equals("")) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                destroyData();          // Jalankan perintah hapus di database
                lsDtbuku();             // Refresh tabel
                clearForm();            // Kosongkan form input
                fieldEnabled(false);    // Nonaktifkan field input
                tombol(false);          // Nonaktifkan tombol aksi
                cBARU.setEnabled(true);
                cTUTUP.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } catch (SQLException ex) {
                Logger.getLogger(Sehat.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus terlebih dahulu.");
    }


    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
       int opsi = JOptionPane.showOptionDialog(this, "Yakin akan Menup Form", "Konfirmasi Tutup Form", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if(opsi == JOptionPane.YES_OPTION)
        System.exit(0);
        
       
    }//GEN-LAST:event_cTUTUPActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
                                             
    int row = tabelData.getSelectedRow();
    if (row != -1) {
        txusername.setText(tabelData.getValueAt(row, 0).toString());
        txpassword.setText(tabelData.getValueAt(row, 1).toString());
        txnotelepon.setText(tabelData.getValueAt(row, 2).toString());
        txemail.setText(tabelData.getValueAt(row, 3).toString());

        cUBAH.setEnabled(true);
        cHAPUS.setEnabled(true);
    }


    }//GEN-LAST:event_tabelDataMouseClicked

    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed
                                            
    if(cBARU.getText().equals("Baru")){
        cBARU.setText("Simpan");
        cTUTUP.setText("Batal");
        cUBAH.setEnabled(false);
        cHAPUS.setEnabled(false);
        clearForm();
        fieldEnabled(true);
    } else {
        if(!txusername.getText().equals("")){
            try {
                // Simpan ke database
                storeData();

                // Ambil data dari form
                String username = txusername.getText();
                String password = txpassword.getText();
                String notelepon = txnotelepon.getText();
                String email = txemail.getText();

                // Tambahkan ke tabel
                DefaultTableModel model = (DefaultTableModel) tabelData.getModel();
                model.addRow(new Object[]{username, password, notelepon, email});

                // Optional: refresh data dari database jika pakai lsDtbuku()
                // lsDtbuku(); 
                
            } catch (SQLException ex) {
                Logger.getLogger(Sehat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        cBARU.setText("Baru");
        cTUTUP.setText("Tutup");
        clearForm();
        fieldEnabled(false);
    }


    }//GEN-LAST:event_cBARUActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed
         if (!txusername.getText().equals("")) {
        fieldEnabled(true); // ✅ Aktifkan semua field supaya bisa diketik dulu
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menyimpan perubahan data ini?", "Konfirmasi Ubah", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                updateData();            // simpan ke database
                lsDtbuku();              // refresh tabel
                clearForm();             // kosongkan form
                fieldEnabled(false);     // kunci kembali field
                tombol(false);           // matikan tombol
                cBARU.setEnabled(true);  // aktifkan tombol Baru
                cTUTUP.setEnabled(true); // aktifkan tombol Tutup
                JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
            } catch (SQLException ex) {
                Logger.getLogger(Sehat.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin diubah terlebih dahulu.");
    }
    }//GEN-LAST:event_cUBAHActionPerformed

    private void txpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sehat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Sehat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Sehat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBARU;
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cTUTUP;
    private javax.swing.JButton cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txnotelepon;
    private javax.swing.JTextField txpassword;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables


}
